from app.graph.state import CopilotState
from app.graph.nodes.common import build_context, llm_try


def patch_generation_node(state: CopilotState) -> CopilotState:
    context = state.get("retrieved_context", [])
    if not context:
        return {"patch": "No patch generated because retrieval returned no context."}

    top = context[0]
    path = top.get("path", "unknown.py")
    query = str(state.get("query", "")).strip()
    refactor_plan = str(state.get("refactor_plan", "")).strip()
    generated = ""
    if query or refactor_plan:
        prompt = (
            "Generate a minimal unified diff patch aligned with the requested refactor/debug goal. "
            "Output only valid diff text. "
            f"User request: {query}\n"
            f"Refactor plan: {refactor_plan}"
        )
        generated = llm_try(prompt=prompt, context=build_context(context, limit=4, max_chars=7000))
    if generated and generated.startswith("diff --git"):
        return {"patch": generated}

    patch = (
        "diff --git a/{path} b/{path}\n"
        "--- a/{path}\n"
        "+++ b/{path}\n"
        "@@\n"
        "-# Existing implementation\n"
        "+# Refactor suggestion generated by Patch Agent\n"
        "+# Apply targeted extraction and improve guard clauses based on retrieved context\n"
    ).format(path=path)

    return {"patch": patch}
