import logging
import re

from app.graph.state import CopilotState
from app.graph.nodes.common import build_context, llm_try


logger = logging.getLogger(__name__)


def patch_generation_node(state: CopilotState) -> CopilotState:
    logger.debug("graph_patch_generation - request")
    context = state.get("retrieved_context", [])
    if not context:
        return {
            "patch": "No patch generated because retrieval returned no context.",
            "patch_proposal": {
                "title": "No patch proposal generated",
                "summary": "Retrieval returned no context, so no safe patch could be proposed.",
                "diff": "",
                "files": [],
                "intent": "patch_generation",
            },
        }

    top = context[0]
    path = top.get("path", "unknown.py")
    query = str(state.get("query", "")).strip()
    refactor_plan = str(state.get("refactor_plan", "")).strip()
    generated = ""
    if query or refactor_plan:
        prompt = (
            "Generate a production-grade unified diff patch aligned with the request. "
            "Return only diff text beginning with 'diff --git'. "
            f"User request: {query}\n"
            f"Refactor plan: {refactor_plan}"
        )
        generated = llm_try(prompt=prompt, context=build_context(context, limit=4, max_chars=7000))

    generated = generated.strip()
    if generated.startswith("```"):
        generated = re.sub(r"^```(?:diff)?\n", "", generated)
        generated = re.sub(r"\n```$", "", generated)

    if generated and generated.startswith("diff --git"):
        files = [line.replace("+++ b/", "", 1).strip() for line in generated.splitlines() if line.startswith("+++ b/")]
        proposal = {
            "title": f"Patch proposal for: {query[:72]}" if query else "Patch proposal",
            "summary": refactor_plan or "Generated a patch proposal from retrieved context and requested change.",
            "diff": generated,
            "files": files,
            "intent": "patch_generation",
        }
        logger.debug("graph_patch_generation - generated structured proposal files=%s", len(files))
        return {"patch": generated, "patch_proposal": proposal}

    patch = (
        "diff --git a/{path} b/{path}\n"
        "--- a/{path}\n"
        "+++ b/{path}\n"
        "@@\n"
        "-# Existing implementation\n"
        "+# Refactor suggestion generated by Patch Agent\n"
        "+# Apply targeted extraction and improve guard clauses based on retrieved context\n"
    ).format(path=path)

    logger.debug("graph_patch_generation - using fallback patch")
    return {
        "patch": patch,
        "patch_proposal": {
            "title": f"Patch proposal for: {query[:72]}" if query else "Patch proposal",
            "summary": "Fallback patch template generated. Review and refine before applying.",
            "diff": patch,
            "files": [path],
            "intent": "patch_generation",
        },
    }
