from app.graph.state import CopilotState


def patch_generation_node(state: CopilotState) -> CopilotState:
    context = state.get("retrieved_context", [])
    if not context:
        return {"patch": "No patch generated because retrieval returned no context."}

    top = context[0]
    patch = (
        "diff --git a/{path} b/{path}\n"
        "--- a/{path}\n"
        "+++ b/{path}\n"
        "@@\n"
        "-# TODO: existing code\n"
        "+# Refactor suggestion generated by Patch Agent\n"
    ).format(path=top.get("path", "unknown.py"))

    return {"patch": patch}
